In [1]:
import numpy as np
import pandas as pd

train_set = pd.read_csv('./dataset/train.csv').sample(frac=1.0)
test_set = pd.read_csv('./dataset/test.csv')
train_set.head(10)

,时间,小区名,小区房屋出租数量,楼层,总楼层,房屋面积,房屋朝向,居住状态,卧室数量,厅的数量,卫的数量,出租方式,区,位置,地铁线路,地铁站点,距离,装修情况,月租金
165655,3,6097,0.187500,2,0.527273,0.000993,北,3.0,3,1,1,0.0,10.0,69.0,4.0,6.0,0.679167,2.0,2.852292
129076,3,5841,0.234375,1,0.581818,0.019033,东南,NaN,3,2,2,NaN,1.0,38.0,NaN,NaN,NaN,NaN,10.696095
145637,3,3895,0.246094,2,0.563636,0.011586,北,NaN,2,2,1,NaN,12.0,52.0,NaN,NaN,NaN,NaN,8.319185
193977,3,2581,0.167969,0,0.181818,0.019033,南,NaN,3,2,2,NaN,1.0,148.0,NaN,NaN,NaN,NaN,7.300509
21859,1,3063,0.023438,2,0.545455,0.008606,东,NaN,1,1,1,NaN,12.0,71.0,5.0,36.0,0.783333,NaN,8.998302
141274,3,6199,0.019531,1,0.527273,0.011255,西,NaN,2,1,1,NaN,3.0,3.0,1.0,101.0,0.720000,NaN,5.602716
171328,3,2411,0.070312,2,0.563636,0.007117,西南,NaN,1,1,1,NaN,14.0,53.0,NaN,NaN,NaN,NaN,2.886248
155497,3,1057,0.132812,2,0.290909,0.006289,南,NaN,1,1,1,NaN,3.0,14.0,NaN,NaN,NaN,NaN,6.960951
189164,3,1383,0.398438,2,0.309091,0.007448,东,NaN,1,1,1,NaN,10.0,85.0,1.0,77.0,0.850833,NaN,7.300509
104617,2,602,0.035156,2,0.581818,0.020523,东,NaN,3,2,2,NaN,12.0,62.0,5.0,14.0,0.416667,NaN,8.998302

In [2]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 196539 entries, 165655 to 43624
Data columns (total 19 columns):
时间          196539 non-null int64
小区名         196539 non-null int64
小区房屋出租数量    195538 non-null float64
楼层          196539 non-null int64
总楼层         196539 non-null float64
房屋面积        196539 non-null float64
房屋朝向        196539 non-null object
居住状态        20138 non-null float64
卧室数量        196539 non-null int64
厅的数量        196539 non-null int64
卫的数量        196539 non-null int64
出租方式        24230 non-null float64
区           196508 non-null float64
位置          196508 non-null float64
地铁线路        91778 non-null float64
地铁站点        91778 non-null float64
距离          91778 non-null float64
装修情况        18492 non-null float64
月租金         196539 non-null float64
dtypes: float64(12), int64(6), object(1)
memory usage: 30.0+ MB

In [3]:
cols_oh = ['小区名','房屋朝向',
          ]
cols_oh_train = cols_oh+['月租金']
cols_oh_test = cols_oh+['id']
cols_fill_0 = ('装修情况')
cols_fill_None = [] #？？？
cols_fill_mean = ['区','地铁线路','地铁站点',
                  '小区房屋出租数量','位置','距离',
                 '居住状态','出租方式']
# cols_nums = ['时间','小区房屋出租数量','楼层','总楼层','房屋面积','卧室数量','厅的数量','卫的数量','距离','装修情况']

X_train = train_set.drop(cols_oh_train, axis=1)
y_train = train_set['月租金']
X_test = test_set.drop(cols_oh_test, axis=1)

X_train[cols_fill_0].fillna(0, inplace=True) 
X_test[cols_fill_0].fillna(0, inplace=True) 

for col in cols_fill_mean:
    X_train[col].fillna(train_set[col].mean(), inplace=True)  
    X_test[col].fillna(train_set[col].mean(), inplace=True) 
for col in cols_fill_None:
    X_train[col].fillna('0', inplace=True)  
    X_test[col].fillna('0', inplace=True)  

cols_oh += cols_fill_None
X_train.shape, X_test.shape,

((196539, 16), (56279, 16))

In [4]:
X_train.head(10)

,时间,小区房屋出租数量,楼层,总楼层,房屋面积,居住状态,卧室数量,厅的数量,卫的数量,出租方式,区,位置,地铁线路,地铁站点,距离,装修情况
165655,3,0.187500,2,0.527273,0.000993,3.000000,3,1,1,0.000000,10.0,69.0,4.00000,6.000000,0.679167,2.0
129076,3,0.234375,1,0.581818,0.019033,2.725196,3,2,2,0.900289,1.0,38.0,3.28485,57.493735,0.551202,0.0
145637,3,0.246094,2,0.563636,0.011586,2.725196,2,2,1,0.900289,12.0,52.0,3.28485,57.493735,0.551202,0.0
193977,3,0.167969,0,0.181818,0.019033,2.725196,3,2,2,0.900289,1.0,148.0,3.28485,57.493735,0.551202,0.0
21859,1,0.023438,2,0.545455,0.008606,2.725196,1,1,1,0.900289,12.0,71.0,5.00000,36.000000,0.783333,0.0
141274,3,0.019531,1,0.527273,0.011255,2.725196,2,1,1,0.900289,3.0,3.0,1.00000,101.000000,0.720000,0.0
171328,3,0.070312,2,0.563636,0.007117,2.725196,1,1,1,0.900289,14.0,53.0,3.28485,57.493735,0.551202,0.0
155497,3,0.132812,2,0.290909,0.006289,2.725196,1,1,1,0.900289,3.0,14.0,3.28485,57.493735,0.551202,0.0
189164,3,0.398438,2,0.309091,0.007448,2.725196,1,1,1,0.900289,10.0,85.0,1.00000,77.000000,0.850833,0.0
104617,2,0.035156,2,0.581818,0.020523,2.725196,3,2,2,0.900289,12.0,62.0,5.00000,14.000000,0.416667,0.0

In [5]:
#标准化
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler((0,1))
mms.fit(X_train)

X_train = mms.transform(X_train)
X_test = mms.transform(X_test)

'''
X_train_mms = mms.transform(X_train[cols_nums])
X_test_mms = mms.transform(X_test[cols_nums])

# 替换为归一化之后的属性值
X_train[cols_nums] = X_train_mms[cols_nums]
X_test[cols_nums] = X_tesr_mms[cols_nums]
'''
print()

In [6]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,LabelBinarizer #要先转化为数值，再onehot
def get_oh(cols): #输入需要onehot的list
#     global X_train_oh, X_test_oh
    X_train_oh = np.arange(X_train.shape[0]).reshape(X_train.shape[0],1)
    X_test_oh = np.arange(X_test.shape[0]).reshape(X_test.shape[0],1)
    
    for col in cols:     
        
        col_train = train_set[col]#.astype('str')
        col_test = test_set[col]#.astype('str')
        
        oh_fea = LabelBinarizer().fit(col_train) #去onehot特征
        train_oh = oh_fea.transform(col_train)
        test_oh = oh_fea.transform(col_test)        
        print(col,'：',train_oh.shape, test_oh.shape)
        
        X_train_oh = np.append(X_train_oh, train_oh, axis=1)
        X_test_oh = np.append(X_test_oh, test_oh, axis=1)
    
    np.delete(X_train_oh, 0, axis=1) #因为刚初始化时多了一个arange
    np.delete(X_test_oh, 0, axis=1)
    return X_train_oh, X_test_oh

X_train_oh, X_test_oh = get_oh(cols_oh[:])

# 这是先先数值化再onehot的
# direct_train_labelencoded = LabelEncoder().fit_transform(direct_train) #数值化
# print(direct_train_labelencoded, direct_train_labelencoded.shape)
# oh = OneHotEncoder(sparse=False).fit(direct_train_labelencoded.reshape(-1,1)) #要转化为(xxx,1)
# direct_oh = oh.transform(direct_train_labelencoded.reshape(-1,1)) 

# direct_train_oh, direct_test_oh = get_oh('房屋朝向')
# name_train_oh, name_test_oh = get_oh('小区名')

小区名 ： (196539, 5547) (56279, 5547)
房屋朝向 ： (196539, 64) (56279, 64)

In [7]:
#小区名太多。。。单独处理
# X_train_oh_name, X_test_oh_name = get_oh([cols_oh[0]]) #因为只有一个值，要加上括号

# from sklearn.decomposition import PCA
# pca = PCA(n_components=1000)
# X_train_oh_name

In [8]:
X_train.shape, X_train_oh.shape

((196539, 16), (196539, 5612))

In [9]:
#合并两个 X
X_train = np.append(X_train, X_train_oh, axis=1)
X_test = np.append(X_test, X_test_oh, axis=1)
# 5924

#合并多个 
# X_train = np.hstack((X_train, direct_train_oh, name_train_oh)) #横向合并
# X_test = np.hstack((X_test, direct_test_oh, name_test_oh)) #横向合并
X_train.shape, X_test.shape,

((196539, 5628), (56279, 5628))

In [10]:
# dir_index = direct_train.value_counts().index
# list(dir_index)

In [11]:
# 划分数据，调参

# from sklearn.model_selection import train_test_split
# X_train2, X_test2, y_train2, y_test2 = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [12]:
from sklearn import svm
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
import time
start = time.time()

# reg = svm.LinearSVR()
reg = RandomForestRegressor(n_estimators=100, n_jobs=-1) #10:122s; 100:665s
reg.fit(X_train, y_train, )
# 交叉验证
# score = cross_val_score(reg, X_train, y_train, cv=3,  n_jobs=-1)
# print(score)

# y_pred = reg.predict(X_test2)
# mse = mean_squared_error(y_test2, y_pred)
# mse
print(time.time() - start)
reg

665.6916337013245

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [13]:
y_pred = reg.predict(X_test)
y_pred.shape

(56279,)

In [14]:
with open('output.csv', 'w') as f:
    f.write('id,price'+'\n')
    for i in range(len(y_pred)):
        f.write(str(i+1)+','+str(y_pred[i])+'\n')